# Generated by Django 6.0.5 on 2026-05-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_companyinfo_logo_contact_photo_alter_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.IntegerField(help_text='Введите число, например 15'),
        ),
    ]
