# Generated by Django 6.0.5 on 2026-05-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_dictionary_options_remove_companyinfo_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={'verbose_name': 'Условие', 'verbose_name_plural': 'Условия сотрудничества'},
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/', verbose_name='Изображение'),
        ),
    ]
