# Generated by Django 6.0.5 on 2026-05-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_dictionary_options_serviceitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='company_images/', verbose_name='Логотип/Фото'),
        ),
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_images/', verbose_name='Фото сотрудника'),
        ),
    ]
